export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Product } from './Product/Products'
export { default as SelectedProduct } from './SelectedProduct/SelectedProduct'
export { default as Services } from './Services/Services'
export { default as CoWorkers } from './CoWorkers/CoWorkers'
export { default as Contact } from './Contact/Contact'